#!/bin/bash -lv

case "$DISTRO_NAME" in
    centos* | rhel*)
	yum install -y cuda=${DIB_NVIDIA_CUDA_VERSION}
	;;
    fedora*)
	dnf install -y cuda=${DIB_NVIDIA_CUDA_VERSION}
	;;
    ubuntu* | debian*)
	apt-get -y install cuda=${DIB_NVIDIA_CUDA_VERSION}
	;;
    *)
	echo "Distro \"$DISTRO_NAME\" is not recognised"
	exit -1
	;;
esac

exit 0
