#!/bin/bash -lv
add-apt-repository 'deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64 /'
add-apt-repository 'deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /'
